import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import categoriesRouter from "./categories";
import productsRouter from "./products";
import chatRouter from "./chat";
import adminRouter from "./admin";
import storiesRouter from "./stories";
import otpRouter from "./otp";
import sendMessageRouter from "./send-message";
import followsRouter from "./follows";
import ordersRouter from "./orders";
import notificationsRouter from "./notifications";
import wasenderApiRouter from "./wasender-api";
import storageRouter from "./storage";
import bannersRouter from "./banners";
import uploadRouter from "./upload";
import reportsRouter from "./reports";
import blocksRouter from "./blocks";
import wishlistRouter from "./wishlist";
import flashSalesRouter from "./flash-sales";
import subscriptionsRouter from "./subscriptions";
import promotionsRouter from "./promotions";
import ridesRouter from "./rides";
import walletRouter from "./wallet";
import userRolesRouter from "./user-roles";
import restaurantsRouter from "./restaurants";
import pharmacyRouter from "./pharmacy";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(otpRouter);
router.use(usersRouter);
router.use(categoriesRouter);
router.use(productsRouter);
router.use(chatRouter);
router.use(adminRouter);
router.use(storiesRouter);
router.use(sendMessageRouter);
router.use(followsRouter);
router.use(ordersRouter);
router.use(notificationsRouter);
router.use(storageRouter);
router.use(bannersRouter);
router.use(uploadRouter);
router.use(reportsRouter);
router.use(blocksRouter);
router.use(wishlistRouter);
router.use(flashSalesRouter);
router.use(subscriptionsRouter);
router.use(promotionsRouter);
router.use(ridesRouter);
router.use(walletRouter);
router.use(userRolesRouter);
router.use(restaurantsRouter);
router.use(pharmacyRouter);
router.use(wasenderApiRouter);

export default router;
